version: "3.6"

services:
  mongosetup:
    image: mongo
    depends_on:
      - mongo1
      - mongo2
    volumes:
      - .:/scripts
    restart: on-failure
    networks:
      - my-mongo-cluster
    entrypoint: [ "bash", "/scripts/mongo_setup.sh"]

  mongo1:
    hostname: mongo1
    container_name: localmongo1
    image: mongo
    ports:
      - 27017:27017
    expose:
      - 27017
    networks:
      - my-mongo-cluster
    entrypoint: [ "/usr/bin/mongod", "--bind_ip_all", "--replSet", "rs0", "--journal", "--dbpath", "/data/db", "--enableMajorityReadConcern", "false" ]
    volumes:
      - mongo1_data:/data/db

  mongo2:
    hostname: mongo2
    container_name: localmongo2
    image: mongo
    ports:
      - 27018:27017
    expose:
      - 27017
    networks:
      - my-mongo-cluster
    entrypoint: [ "/usr/bin/mongod", "--bind_ip_all", "--replSet", "rs0", "--journal", "--dbpath", "/data/db", "--enableMajorityReadConcern", "false" ]
    volumes:
      - mongo2_data:/data/db

networks:
  my-mongo-cluster:
    driver: bridge

volumes:
  mongo1_data:
  mongo2_data:
