version: "3.6"

services:
  mongo1:
    hostname: mongo1
    container_name: localmongo1
    image: mongo
    ports:
      - 27017:27017
    expose:
      - 27017
    restart: always
    networks: 
      - my-mongo-cluster
    entrypoint: [ "/usr/bin/mongod", "--bind_ip_all", "--replSet", "rs0" ]

  mongo2:
    hostname: mongo2
    container_name: localmongo2
    image: mongo
    ports:
      - 27018:27018
    expose:
      - 27018
    restart: always
    networks: 
      - my-mongo-cluster
    entrypoint: [ "/usr/bin/mongod", "--bind_ip_all", "--replSet", "rs0" ]

  mongo3:
    hostname: mongo3
    container_name: localmongo3
    image: mongo
    ports:
      - 27019:27019
    expose:
      - 27019
    restart: always
    networks: 
      - my-mongo-cluster
    entrypoint: [ "/usr/bin/mongod", "--bind_ip_all", "--replSet", "rs0" ]

  mongosetup:
    image: mongo
    depends_on:
      - mongo1
      - mongo2
      - mongo3
    volumes:
      - .:/scripts
    restart: "no"
    networks: 
      - my-mongo-cluster
    entrypoint: [ "bash", "/scripts/mongo_setup.sh"]

networks: 
  my-mongo-cluster:
    driver: bridge
