version: "3.6"

services:
  mongosetup:
    image: registry.tce.ro.gov.br/mongo-cluster-setup:v1.1.0
    restart: "on-failure"
    depends_on:
      - mongo1
      - mongo2
    networks:
      - app

  mongo1:
    hostname: mongo1
    image: mongo:4.4.0-bionic
    restart: "always"
    networks:
      - app
    entrypoint: [ "/usr/bin/mongod", "--bind_ip_all", "--replSet", "rs0", "--journal", "--dbpath", "/data/db", "--enableMajorityReadConcern", "true"]
    volumes:
      - mongo1_data/db:/data/db
      - mongo1_data/configdb:/data/db

  mongo2:
    hostname: mongo2
    image: mongo:4.4.0-bionic
    restart: "always"
    networks:
      - app
    entrypoint: [ "/usr/bin/mongod", "--bind_ip_all", "--replSet", "rs0", "--journal", "--dbpath", "/data/db", "--enableMajorityReadConcern", "true"]
    volumes:
      - mongo2_data/db:/data/db
      - mongo2_data/configdb:/data/db

  mongo3:
    hostname: mongo3
    image: mongo:4.4.0-bionic
    restart: "always"
    networks:
      - app
    entrypoint: [ "/usr/bin/mongod", "--bind_ip_all", "--replSet", "rs0", "--journal", "--dbpath", "/data/db", "--enableMajorityReadConcern", "true"]
    volumes:
      - mongo3_data/db:/data/db
      - mongo3_data/configdb:/data/db

networks:
  app:
    external: true

volumes:
  mongo1_data:
    driver: local
  mongo2_data:
    driver: local
  mongo3_data:
    driver: local
