version: "3.6"

services:
  mongo1:
    hostname: mongo1
    image: mongo
    restart: always
    networks: 
      - app
    entrypoint: [ "/usr/bin/mongod", "--bind_ip_all", "--replSet", "rs0" ]

  mongo2:
    hostname: mongo2
    image: mongo
    restart: always
    networks: 
      - app
    entrypoint: [ "/usr/bin/mongod", "--bind_ip_all", "--replSet", "rs0" ]

  mongo3:
    hostname: mongo3
    image: mongo
    networks: 
      - app
    entrypoint: [ "/usr/bin/mongod", "--bind_ip_all", "--replSet", "rs0" ]

  mongosetup:
    image: registry.tce.ro.gov.br/mongo-cluster-setup:v1.0.1
    depends_on:
      - mongo1
      - mongo2
      - mongo3
    restart: "no"
    networks: 
      - app

networks:
  app: 
    external: true
